controller_manager:
  ros__parameters:
    update_rate: 20 # Hz
    hermes_base_control:
      type: diff_drive_controller/DiffDriveController
    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    scara_controller:
      type: joint_trajectory_controller/JointTrajectoryController
    gripper_controller:
      type: joint_trajectory_controller/JointTrajectoryController

/**/hermes_base_control:
  ros__parameters:
    type: diff_drive_controller/DiffDriveController
    use_stamped_vel: false
    use_sim_time: true
    publish_rate: 50.0
    left_wheel_names: ["wheel_f_l_center_plane_joint", "wheel_b_l_center_plane_joint", "wheel_c_l_center_plane_joint"]
    right_wheel_names: ["wheel_f_r_center_plane_joint", "wheel_b_r_center_plane_joint", "wheel_c_r_center_plane_joint"]
    wheel_separation: 1.0
    wheel_radius: 0.375
    wheel_separation_multiplier: 1.0
    left_wheel_radius_multiplier: 1.0
    right_wheel_radius_multiplier: -1.0
    base_frame_id: base_footprint
    enable_odom_tf: true
    publish_limited_velocity: true
    linear:
      x:
        has_velocity_limits: true
        max_velocity: 3.0
        has_acceleration_limits: true
        max_acceleration: 3.0
    angular:
      z:
        has_velocity_limits: true
        max_velocity: 3.0
        has_acceleration_limits: true
        max_acceleration: 3.0

/**/scara_controller:
  ros__parameters:
    joints:
      - arm_joint1_link_joint
      - arm_joint3_joint
      - arm_link5_joint
      - gripper_base_joint
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
    allow_nonzero_velocity_at_trajectory_end: true
/**/gripper_controller:
  ros__parameters:
    joints:
      - gripper_finger_left_joint
      - gripper_finger_right_joint
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
    allow_nonzero_velocity_at_trajectory_end: true
